# Generated by Django 5.1.3 on 2024-11-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="type",
            field=models.CharField(default="website", max_length=50),
        ),
        migrations.AddField(
            model_name="link",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
